"""
A module defining an abstract base class for a render backend.

This module contains the `RenderBackend` class, which serves as a
base for implementing rendering operations including enabling and
disabling capabilities, setting blend functions, and managing depth
and material settings. It provides an interface for rendering tasks,
but requires a concrete implementation to define specific behavior.
"""

from abc import ABC


class RenderBackend(ABC):
    """Render Backend"""
    def enable(self, cap): ...
    def disable(self, cap): ...
    def is_enabled(self, cap): ...
    def set_blend_func(self, src, dst): ...
    def set_depth_mask(self, flag: bool): ...
    def get_depth_mask(self) -> bool: ...
    def set_material(self, face: Any, mat: Any): ...