"""
GL Backend Interface.

This module provides an interface for a GL backend implementation, which
offers functionalities for managing OpenGL state, drawing meshes, managing
materials, handling client-side arrays, and interacting with textures.

Classes:
    GLBackend: A class defining the interface for the GL backend with
               various methods for rendering and managing rendering states.
"""

class GLBackend:
    """GL Backend Interface"""
    def enable(self, cap): ...
    def disable(self, cap): ...
    def draw_mesh(self, ctx: "RenderContext"): ...
    def set_material(self, mat): ...

    def set_line_width(self, width: float): ...
    def set_polygon_mode(self, face, mode): ...

    # --- Fixed function color ---
    def set_color(self, rgba: tuple[float, float, float, float]): ...

    # --- Client arrays ---
    def enable_vertex_array(self): ...
    def set_vertex_pointer(self, data): ...

    def enable_normal_array(self): ...
    def set_normal_pointer(self, data): ...

    def enable_color_array(self): ...
    def set_color_pointer(self, data, size: int): ...

    def enable_texcoord_array(self): ...
    def set_texcoord_pointer(self, data): ...

    # --- Drawing ---
    def draw_elements(self, mode, indices): ...

    # --- Textures ---
    def bind_texture(self, texture_id): ...