
import numpy as np
from math import sin, cos
from OpenGL.GL import *
from OpenGL.GLUT import *
from OpenGL.GLU import *
# Optional: if you want to demonstrate templating
from jinja2 import Template

# -------------------------------
# Quad data (two triangles) with normals
# -------------------------------
# Quad in the XY plane, at z = -5
# We'll define four corners and two triangles (0-1-2 and 2-3-0)
quad_verts = [
    {'pos': [-1.0,  1.0, -5.0], 'normal': [0.0, 0.0, 1.0]},  # top-left
    {'pos': [ 1.0,  1.0, -5.0], 'normal': [0.0, 0.0, 1.0]},  # top-right
    {'pos': [ 1.0, -1.0, -5.0], 'normal': [0.0, 0.0, 1.0]},  # bottom-right
    {'pos': [-1.0, -1.0, -5.0], 'normal': [0.0, 0.0, 1.0]},  # bottom-left
]

# Indices for two triangles
quad_indices = [
    (0, 1, 2),
    (2, 3, 0),
]

# Uniforms (we'll rotate model around Y and X with mouse)
model = np.identity(4, dtype=np.float32)
view  = np.identity(4, dtype=np.float32)
proj  = np.identity(4, dtype=np.float32)

# Camera-ish projection
def update_projection(width, height):
    glMatrixMode(GL_PROJECTION)
    glLoadIdentity()
    aspect = width / float(height) if height > 0 else 1.0
    gluPerspective(45.0, aspect, 0.1, 100.0)
    glMatrixMode(GL_MODELVIEW)

# -------------------------------
# Optional: a tiny Jinja2-inspired per-vertex template
# This is illustrative; we compute in Python for reliability here.
# -------------------------------
template_src = """
# Vertex preface (generated by Jinja)
pos: {{ pos }}
normal: {{ normal }}

# Compute color from normal
color = [ (n[0]*0.5)+0.5, (n[1]*0.5)+0.5, (n[2]*0.5)+0.5 ]
"""
template = Template(template_src)

def render_vertex_with_template(v, mvp):
    # This demonstrates where you could render a template per-vertex.
    # For now, we compute directly; the template is shown for educational purposes.
    # Build a 4D pos
    p = v['pos'] + [1.0]
    # MVP-like transform: p' = MVP * p
    # Compute using numpy for accuracy
    gl_pos = (mvp @ np.array(p, dtype=np.float32)).tolist()
    # Color from normal
    n = np.array(v['normal'], dtype=float)
    nm = np.linalg.norm(n)
    if nm != 0:
        n_norm = (n / nm).tolist()
    else:
        n_norm = n.tolist()
    color = [(n_norm[0]*0.5)+0.5, (n_norm[1]*0.5)+0.5, (n_norm[2]*0.5)+0.5]
    return {'gl_pos': gl_pos, 'color': color}

# -------------------------------
# Interaction: mouse-driven rotation
# -------------------------------
rot_x, rot_y = 0.0, 0.0
dragging = False
last_x, last_y = 0, 0

def mouse(button, state, x, y):
    global dragging, last_x, last_y
    if button == GLUT_LEFT_BUTTON:
        if state == GLUT_DOWN:
            dragging = True
            last_x, last_y = x, y
        else:
            dragging = False

def motion(x, y):
    global rot_x, rot_y, last_x, last_y
    if dragging:
        dx = x - last_x
        dy = y - last_y
        last_x, last_y = x, y
        # Update rotation angles (sensitivity)
        rot_y += dx * 0.5
        rot_x += dy * 0.5
        glutPostRedisplay()

def keyboard(key, x, y):
    if key == b'\x1b':  # ESC
        sys.exit()

# -------------------------------
# OpenGL setup and render loop
# -------------------------------
def init_gl():
    glClearColor(0.15, 0.15, 0.2, 1.0)
    glEnable(GL_DEPTH_TEST)
    glShadeModel(GL_SMOOTH)

def display():
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
    glLoadIdentity()

    # Simple camera: place back a bit and apply rotations
    glTranslatef(0.0, 0.0, -8.0)

    # Apply rotations from mouse
    glRotatef(rot_x, 1.0, 0.0, 0.0)
    glRotatef(rot_y, 0.0, 1.0, 0.0)

    # Optional: emulate "MVP" by building a model-view-projection using fixed-function
    # Since we're using fixed-function, we just rely on these transforms above.

    # Compute per-vertex outputs (CPU-side)
    # We create mvp for demonstration (identity here plus the above transforms)
    # In this simple demo, we'll just use the pre-transforms by OpenGL.
    # We'll still compute a color per vertex from their normals.

    glBegin(GL_TRIANGLES)
    for idx in quad_indices:
        for i in idx:
            v = quad_verts[i]
            # Compute color from normal (same as CPU)
            n = np.array(v['normal'], dtype=float)
            nm = np.linalg.norm(n)
            if nm != 0:
                n_norm = (n / nm).tolist()
            else:
                n_norm = n.tolist()
            color = [(n_norm[0]*0.5)+0.5, (n_norm[1]*0.5)+0.5, (n_norm[2]*0.5)+0.5]
            glColor3f(*color)
            glVertex3f(v['pos'][0], v['pos'][1], v['pos'][2])
    glEnd()

    glutSwapBuffers()

def reshape(width, height):
    if height == 0:
        height = 1
    glViewport(0, 0, width, height)
    glMatrixMode(GL_PROJECTION)
    glLoadIdentity()
    aspect = width / float(height)
    gluPerspective(45.0, aspect, 0.1, 100.0)
    glMatrixMode(GL_MODELVIEW)
    glLoadIdentity()

def main():
    glutInit(sys.argv)
    glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA | GLUT_DEPTH)
    glutInitWindowSize(800, 600)
    glutCreateWindow(b"Quad with mouse rotation - PyOpenGL + GLUT (legacy GL)")

    init_gl()
    glutDisplayFunc(display)
    glutReshapeFunc(reshape)
    glutMouseFunc(mouse)
    glutMotionFunc(motion)
    glutKeyboardFunc(keyboard)

    # Initial projection setup (in reshape)
    glutMainLoop()

if __name__ == "__main__":
    main()
