
import numpy as np
from OpenGL.GL import *
from OpenGL.GLUT import *
from OpenGL.GLU import *
from jinja2 import Template

# -------------------------------
# Minimal data model: a single triangle
# -------------------------------
vertices = [
    {'pos': [ 0.0,  0.5, -2.0], 'normal': [0.0, 0.0, 1.0]},
    {'pos': [-0.5, -0.5, -2.0], 'normal': [0.0, 0.0, 1.0]},
    {'pos': [ 0.5, -0.5, -2.0], 'normal': [0.0, 0.0, 1.0]},
]

uniforms = {
    'model': np.identity(4, dtype=np.float32),
    'view' : np.identity(4, dtype=np.float32),
    'proj' : np.identity(4, dtype=np.float32),
}

# The tiny Jinja2 template to compute per-vertex data
template_src = """
# Vertex preface (generated by Jinja)
# pos: {{ pos }}
# normal: {{ normal }}

{% set p = pos + [1.0] %}
{% set world = (model @ p) %}
{% set eye   = (view  @ world) %}
{% set clip  = (proj  @ eye) %}
gl_pos = {{ clip }}
{% set n = normal %}
{% set color = [(n[0]*0.5)+0.5, (n[1]*0.5)+0.5, (n[2]*0.5)+0.5] %}
v_color = {{ color }}
"""

# The template environment; a tiny "safe" subset is enough
template = Template(template_src)

# Helpers to do matrix-vector multiply in pure Python (no numpy in the template)
def mat4_mul_vec4_py(M, v):
    M = np.asarray(M, dtype=np.float32)
    v = np.asarray(v, dtype=np.float32)
    return (M @ v).tolist()

# CPU-side render: compute per-vertex outputs
def compute_vertex_outputs(v, uniforms):
    # Simple inline math to avoid parsing the generated template string
    p = v['pos'] + [1.0]
    world = mat4_mul_vec4_py(uniforms['model'], p)
    eye   = mat4_mul_vec4_py(uniforms['view'], world)
    clip  = mat4_mul_vec4_py(uniforms['proj'], eye)
    gl_pos = clip

    n = np.array(v['normal'], dtype=float)
    nm = np.linalg.norm(n)
    if nm != 0:
        n_norm = (n / nm).tolist()
    else:
        n_norm = n.tolist()
    color = [(n_norm[0]*0.5)+0.5, (n_norm[1]*0.5)+0.5, (n_norm[2]*0.5)+0.5]

    return {'gl_pos': gl_pos, 'v_color': color, 'pos': v['pos'], 'normal': v['normal']}

# OpenGL-friendly storage for the per-vertex outputs
rendered_vertices = []

# GLUT / OpenGL callback placeholders
def init_gl():
    glClearColor(0.1, 0.1, 0.15, 1.0)
    glEnable(GL_DEPTH_TEST)

def display():
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)

    glBegin(GL_TRIANGLES)
    for v in rendered_vertices:
        glColor3f(v['v_color'][0], v['v_color'][1], v['v_color'][2])
        glVertex3f(v['pos'][0], v['pos'][1], v['pos'][2])
    glEnd()

    glutSwapBuffers()

def reshape(width, height):
    if height == 0:
        height = 1
    aspect = width / float(height)
    glViewport(0, 0, width, height)
    glMatrixMode(GL_PROJECTION)
    glLoadIdentity()
    # Use a simple perspective to resemble modern behavior
    gluPerspective(45.0, aspect, 0.1, 100.0)
    glMatrixMode(GL_MODELVIEW)
    glLoadIdentity()

def keyboard(key, x, y):
    if key == b'\x1b':  # ESC
        sys.exit()

# -------------------------------
# Main: build per-vertex data via Python (and optionally via Jinja)
# -------------------------------
def main():
    global rendered_vertices

    # Compute the per-vertex outputs using the template approach
    # For demonstration, we'll render using the Python math (no string parsing).
    # If you want to actually render via the Jinja template, you could render
    # to a string and parse it; that is intentionally omitted here for safety.
    for v in vertices:
        rendered = compute_vertex_outputs(v, uniforms)
        rendered_vertices.append(rendered)

    # Initialize GLUT / OpenGL
    glutInit(sys.argv)
    glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA | GLUT_DEPTH)
    glutInitWindowSize(800, 600)
    glutCreateWindow(b"PyOpenGL + GLUT with Jinja-like per-vertex data (legacy GL)")

    init_gl()

    glutDisplayFunc(display)
    glutReshapeFunc(reshape)
    glutKeyboardFunc(lambda k, x, y: keyboard(k, x, y))

    # Enter the main loop
    glutMainLoop()

if __name__ == "__main__":
    main()
