"""
GL Draw Mode
"""

from enum import IntEnum

from OpenGL.GL import (
    GL_LINE_LOOP,
    GL_LINE_STRIP,
    GL_LINE_STRIP_ADJACENCY,
    GL_LINES,
    GL_LINES_ADJACENCY,
    GL_PATCHES,
    GL_POINTS,
    GL_POLYGON,
    GL_QUAD_STRIP,
    GL_QUADS,
    GL_TRIANGLE_STRIP,
    GL_TRIANGLE_STRIP_ADJACENCY,
    GL_TRIANGLES,
    GL_TRIANGLES_ADJACENCY,
    GL_ARRAY_BUFFER,
    GL_STATIC_DRAW, GL_FLOAT, GL_INT,
    GL_DYNAMIC_DRAW, GL_UNSIGNED_INT, GL_UNSIGNED_SHORT,
GL_ELEMENT_ARRAY_BUFFER, GL_UNIFORM_BUFFER, GL_SHADER_STORAGE_BUFFER
)
class GLDataType(IntEnum):
    FLOAT = GL_FLOAT
    INT = GL_INT

class GLIndexType(IntEnum):
    UNSIGNED_INT = GL_UNSIGNED_INT
    UNSIGNED_SHORT = GL_UNSIGNED_SHORT

class GLUsageHint(IntEnum):
    """Usage Hint"""
    STATIC_DRAW = GL_STATIC_DRAW
    DYNAMIC_DRAW = GL_DYNAMIC_DRAW


class GLBufferTarget(IntEnum):
    """GL Buffer Target"""
    ARRAY = GL_ARRAY_BUFFER
    ELEMENT_ARRAY_BUFFER = GL_ELEMENT_ARRAY_BUFFER
    UNIFORM_BUFFER = GL_UNIFORM_BUFFER
    SHADER_STORAGE_BUFFER = GL_SHADER_STORAGE_BUFFER


class GLLegacyPrimitive(IntEnum):
    """Deprecate the GLDramMode versions"""
    QUADS = GL_QUADS
    POLYGON = GL_POLYGON

class GLDrawMode(IntEnum):
    """GL Draw Mode"""

    QUAD_STRIP = GL_QUAD_STRIP
    TRIANGLE_STRIP = GL_TRIANGLE_STRIP
    TRIANGLES = GL_TRIANGLES
    POINTS = GL_POINTS
    LINE_STRIP = GL_LINE_STRIP
    QUADS = GL_QUADS
    POLYGON = GL_POLYGON
    LINES = GL_LINES
    LINE_LOOP = GL_LINE_LOOP
    LINE_STRIP_ADJACENCY = GL_LINE_STRIP_ADJACENCY
    LINES_ADJACENCY = GL_LINES_ADJACENCY
    TRIANGLE_STRIP_ADJACENCY = GL_TRIANGLE_STRIP_ADJACENCY
    TRIANGLES_ADJACENCY = GL_TRIANGLES_ADJACENCY
    PATCHES = GL_PATCHES

    @classmethod
    def choices(cls):
        return [m.value for m in cls]
