"""
GL Draw Mode
"""

from enum import IntEnum, IntFlag
from OpenGL.raw.GL.VERSION.GL_1_0 import GL_POINTS
from OpenGL.raw.GL.VERSION.GL_1_5 import GL_ARRAY_BUFFER
from OpenGL.GL import (
    GL_COLOR_BUFFER_BIT,
    GL_DEPTH_BUFFER_BIT,
    GL_DYNAMIC_DRAW,
    GL_ELEMENT_ARRAY_BUFFER,
    GL_FLOAT,
    GL_INT,
    GL_LINE_BIT,
    GL_LINE_LOOP,
    GL_LINE_STRIP,
    GL_LINE_STRIP_ADJACENCY,
    GL_LINES,
    GL_LINES_ADJACENCY,
    GL_MODELVIEW,
    GL_PATCHES,
    GL_POLYGON,
    GL_PROJECTION,
    GL_QUAD_STRIP,
    GL_QUADS,
    GL_SHADER_STORAGE_BUFFER,
    GL_STATIC_DRAW,
    GL_TRIANGLE_STRIP,
    GL_TRIANGLE_STRIP_ADJACENCY,
    GL_TRIANGLES,
    GL_TRIANGLES_ADJACENCY,
    GL_UNIFORM_BUFFER,
    GL_UNSIGNED_INT,
    GL_UNSIGNED_SHORT,
)
from OpenGL.raw.GL.VERSION.GL_1_0 import GL_CLIP_PLANE0, GL_CLIP_PLANE1


class GLLegacyMatrixMode(IntEnum):
    """GL Matrix Mode"""

    PROJECTION = GL_PROJECTION
    MODELVIEW = GL_MODELVIEW


class GLLegacyClipPlane(IntEnum):
    """Clipping Mode"""
    CLIP_PLANE0 = GL_CLIP_PLANE0
    CLIP_PLANE1 = GL_CLIP_PLANE1


class GLBitMask(IntFlag):
    """GL Bit Mask"""

    LINE = GL_LINE_BIT
    DEPTH_BUFFER = GL_DEPTH_BUFFER_BIT
    COLOR_BUFFER = GL_COLOR_BUFFER_BIT


class GLDataType(IntEnum):
    FLOAT = GL_FLOAT
    INT = GL_INT


class GLIndexType(IntEnum):
    UNSIGNED_INT = GL_UNSIGNED_INT
    UNSIGNED_SHORT = GL_UNSIGNED_SHORT


class GLUsageHint(IntEnum):
    """Usage Hint"""

    STATIC_DRAW = GL_STATIC_DRAW
    DYNAMIC_DRAW = GL_DYNAMIC_DRAW


class GLBufferTarget(IntEnum):
    """GL Buffer Target"""

    ARRAY = GL_ARRAY_BUFFER
    ELEMENT = GL_ELEMENT_ARRAY_BUFFER
    UNIFORM = GL_UNIFORM_BUFFER
    SHADER_STORAGE = GL_SHADER_STORAGE_BUFFER


class GLLegacyPrimitive(IntEnum):
    """Deprecate the GLDramMode versions"""

    QUADS = GL_QUADS
    POLYGON = GL_POLYGON


class GLDrawMode(IntEnum):
    """GL Draw Mode"""

    QUAD_STRIP = GL_QUAD_STRIP
    TRIANGLE_STRIP = GL_TRIANGLE_STRIP
    TRIANGLES = GL_TRIANGLES
    POINTS = GL_POINTS
    LINE_STRIP = GL_LINE_STRIP
    QUADS = GL_QUADS
    POLYGON = GL_POLYGON
    LINES = GL_LINES
    LINE_LOOP = GL_LINE_LOOP
    LINE_STRIP_ADJACENCY = GL_LINE_STRIP_ADJACENCY
    LINES_ADJACENCY = GL_LINES_ADJACENCY
    TRIANGLE_STRIP_ADJACENCY = GL_TRIANGLE_STRIP_ADJACENCY
    TRIANGLES_ADJACENCY = GL_TRIANGLES_ADJACENCY
    PATCHES = GL_PATCHES

    @classmethod
    def choices(cls):
        return [m.value for m in cls]
