"""
GL Draw Mode
"""
from enum import IntEnum

from OpenGL.GL import (GL_LINE_LOOP, GL_LINE_STRIP, GL_LINE_STRIP_ADJACENCY,
                       GL_LINES, GL_LINES_ADJACENCY, GL_PATCHES, GL_POINTS,
                       GL_POLYGON, GL_QUADS, GL_TRIANGLE_STRIP,
                       GL_TRIANGLE_STRIP_ADJACENCY, GL_TRIANGLES,
                       GL_TRIANGLES_ADJACENCY, GL_QUAD_STRIP)


class GLDrawMode(IntEnum):
    """GL Draw Mode"""
    QUAD_STRIP = GL_QUAD_STRIP
    TRIANGLE_STRIP = GL_TRIANGLE_STRIP
    TRIANGLES = GL_TRIANGLES
    POINTS = GL_POINTS
    LINE_STRIP = GL_LINE_STRIP
    QUADS = GL_QUADS
    POLYGON = GL_POLYGON
    LINES = GL_LINES
    LINE_LOOP = GL_LINE_LOOP
    LINE_STRIP_ADJACENCY = GL_LINE_STRIP_ADJACENCY
    LINES_ADJACENCY = GL_LINES_ADJACENCY
    TRIANGLE_STRIP_ADJACENCY = GL_TRIANGLE_STRIP_ADJACENCY
    TRIANGLES_ADJACENCY = GL_TRIANGLES_ADJACENCY
    PATCHES = GL_PATCHES

    @classmethod
    def choices(cls):
        return [m.value for m in cls]